

volumes:
  mariadb-data:
    driver: local
  piwigo-gallery:
    driver: local
  piwigo-data:
    driver: local

services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - 8085:80
    restart: always
    volumes:
      - piwigo-gallery:/gallery
      - piwigo-data:/config
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: piwigo
      MARIADB_USER: piwigo
      MARIADB_PASSWORD: piwigo
      MARIADB_DATABASE: piwigo
    volumes:
      - mariadb-data:/var/lib/mysql

